name: Build EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Ustaw Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Zainstaluj zależności
        run: |
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Zbuduj EXE
        run: pyinstaller --onefile main.py

      - name: Wgraj EXE jako artifact
        uses: actions/upload-artifact@v4
        with:
          name: moj-program
          path: dist/*.exe
